<?php

if (!function_exists('glob_recursive')) {

    // Does not support flag GLOB_BRACE

    function glob_recursive($pattern, $flags = 0)
    {
        $files = glob($pattern, $flags);

        foreach (glob(dirname($pattern) . '/*', GLOB_ONLYDIR | GLOB_NOSORT) as $dir) {
            $files = array_merge($files, glob_recursive($dir . '/' . basename($pattern), $flags));
        }
        return $files;
    }

}

$files = glob_recursive('classes/*.php');


if (!empty($files)) {
        
    $mapping = '<?php' . "\n/* Auto generated by @falexandrou */\nAutoloader::add_classes(array(\n";
    
    foreach ($files as $file) {
        $class = preg_replace('#^(.*)\.php$#i', '$1', $file);
        $namespaces = explode('/', $class);
        $class = implode('\\\\', $namespaces);
        $mapping .= "\t'{$class}'  =>  __DIR__.'/{$file}',\n";
    }
    
    $mapping .= "));\n" . '?>' . "\n";
    $done = file_put_contents('bootstrap.php', $mapping);
    echo $done ? "Bootstrap file generated successfully!\n" : "Something went wrong. Bootstrap file not created\n";
    
    exit;
}

echo "Something went wrong\n";

?>